
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import rss.resources.backend.DatabaseConnection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shuaib UWC
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Products_btn = new javax.swing.JButton();
        SalesClerk_btn = new javax.swing.JButton();
        Statistics = new javax.swing.JButton();
        LogOut_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ProdID = new javax.swing.JLabel();
        ProdNAme = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        Category = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        ProdID_txt = new javax.swing.JTextField();
        ProdName_txt = new javax.swing.JTextField();
        ProdQuantity_txt = new javax.swing.JTextField();
        ProdPrice_txt = new javax.swing.JTextField();
        ProdCategory_txt = new javax.swing.JTextField();
        ProdDescript_txt = new javax.swing.JTextField();
        AddPod_btn = new javax.swing.JButton();
        DeleteProd_btn = new javax.swing.JButton();
        EditProd_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductList = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Products_btn.setBackground(new java.awt.Color(0, 0, 204));
        Products_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Products_btn.setForeground(new java.awt.Color(204, 255, 255));
        Products_btn.setText("PRODUCTS");
        Products_btn.setBorder(null);
        Products_btn.setContentAreaFilled(false);
        Products_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(Products_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, 31));

        SalesClerk_btn.setBackground(new java.awt.Color(0, 0, 204));
        SalesClerk_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SalesClerk_btn.setForeground(new java.awt.Color(204, 255, 255));
        SalesClerk_btn.setText("SALES CLERK");
        SalesClerk_btn.setBorder(null);
        SalesClerk_btn.setContentAreaFilled(false);
        SalesClerk_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalesClerk_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesClerk_btnActionPerformed(evt);
            }
        });
        jPanel2.add(SalesClerk_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 150, 31));

        Statistics.setBackground(new java.awt.Color(0, 0, 204));
        Statistics.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Statistics.setForeground(new java.awt.Color(204, 255, 255));
        Statistics.setText("STATISTICS");
        Statistics.setBorder(null);
        Statistics.setContentAreaFilled(false);
        Statistics.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Statistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatisticsActionPerformed(evt);
            }
        });
        jPanel2.add(Statistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 150, 31));

        LogOut_btn.setBackground(new java.awt.Color(0, 0, 204));
        LogOut_btn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        LogOut_btn.setForeground(new java.awt.Color(255, 0, 0));
        LogOut_btn.setText("LOG OUT");
        LogOut_btn.setBorder(null);
        LogOut_btn.setContentAreaFilled(false);
        LogOut_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut_btnActionPerformed(evt);
            }
        });
        jPanel2.add(LogOut_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 150, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("DESIGNED BY TRENTECH");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 150, 20));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("PRODUCTS");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 11, -1, -1));

        ProdID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ProdID.setForeground(new java.awt.Color(0, 0, 204));
        ProdID.setText("Product ID");
        jPanel3.add(ProdID, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 93, -1, -1));

        ProdNAme.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ProdNAme.setForeground(new java.awt.Color(0, 0, 204));
        ProdNAme.setText("Product Name");
        jPanel3.add(ProdNAme, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 93, -1, -1));

        Quantity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Quantity.setForeground(new java.awt.Color(0, 0, 204));
        Quantity.setText("Quantity");
        jPanel3.add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 93, -1, -1));

        Price.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Price.setForeground(new java.awt.Color(0, 0, 204));
        Price.setText("Price");
        jPanel3.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 139, 64, -1));

        Category.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Category.setForeground(new java.awt.Color(0, 0, 204));
        Category.setText("Category");
        jPanel3.add(Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 139, -1, -1));

        Description.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Description.setForeground(new java.awt.Color(0, 0, 204));
        Description.setText("Description");
        jPanel3.add(Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 139, -1, -1));
        jPanel3.add(ProdID_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 95, 135, 24));
        jPanel3.add(ProdName_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 94, 140, 26));
        jPanel3.add(ProdQuantity_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 94, 150, 27));

        ProdPrice_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdPrice_txtActionPerformed(evt);
            }
        });
        jPanel3.add(ProdPrice_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 141, 135, 24));
        jPanel3.add(ProdCategory_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 140, 140, 26));

        ProdDescript_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdDescript_txtActionPerformed(evt);
            }
        });
        jPanel3.add(ProdDescript_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 140, 150, 27));

        AddPod_btn.setBackground(new java.awt.Color(0, 0, 204));
        AddPod_btn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        AddPod_btn.setForeground(new java.awt.Color(204, 255, 255));
        AddPod_btn.setText("ADD");
        AddPod_btn.setBorder(null);
        AddPod_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddPod_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPod_btnActionPerformed(evt);
            }
        });
        jPanel3.add(AddPod_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 218, 98, 34));

        DeleteProd_btn.setBackground(new java.awt.Color(0, 0, 204));
        DeleteProd_btn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        DeleteProd_btn.setForeground(new java.awt.Color(204, 255, 255));
        DeleteProd_btn.setText("DELETE");
        DeleteProd_btn.setBorder(null);
        DeleteProd_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteProd_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteProd_btnActionPerformed(evt);
            }
        });
        jPanel3.add(DeleteProd_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 218, 88, 34));

        EditProd_btn.setBackground(new java.awt.Color(0, 0, 204));
        EditProd_btn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        EditProd_btn.setForeground(new java.awt.Color(204, 255, 255));
        EditProd_btn.setText("EDIT");
        EditProd_btn.setBorder(null);
        EditProd_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditProd_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProd_btnActionPerformed(evt);
            }
        });
        jPanel3.add(EditProd_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 218, 81, 34));

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("X");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 0, 39, 29));

        ProductList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT ID", "PRODUCT NAME ", "QUANTITY ", "PRICE ", "CATEGORY", "DESCRIPTION "
            }
        ));
        ProductList.setSelectionBackground(new java.awt.Color(0, 0, 204));
        jScrollPane1.setViewportView(ProductList);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 394, 967, 99));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("PRODUCT LIST");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 361, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddPod_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPod_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPod_btnActionPerformed

    private void ProdPrice_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdPrice_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdPrice_txtActionPerformed

    private void ProdDescript_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdDescript_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdDescript_txtActionPerformed

    private void SalesClerk_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesClerk_btnActionPerformed
        setVisible(false);
        new SalesClerk().setVisible(true); 
        // TODO add your handling code here:
    }//GEN-LAST:event_SalesClerk_btnActionPerformed

    private void StatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatisticsActionPerformed
        setVisible(false);
        new Statistics().setVisible(true); 
        // TODO add your handling code here:
    }//GEN-LAST:event_StatisticsActionPerformed

    private void DeleteProd_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteProd_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteProd_btnActionPerformed

    private void LogOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOut_btnActionPerformed
        setVisible(false);
        new LoginPage().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_LogOut_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EditProd_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProd_btnActionPerformed
    
    
    Connection con = DatabaseConnection.getCon();
        
        //Assigning the product name, description, price, stock
        int productID = Integer.parseInt(ProdID_txt.getText());
        String productName = ProdName_txt.getText();
        String productDesc = ProdDescript_txt.getText();
        double priceAdd = Double.parseDouble(ProdPrice_txt.getText());
        int stockAdd = Integer.parseInt(ProdQuantity_txt.getText());

        //Connection connection = connect();
        try{
            //Statement st=con.createStatement();
            
            String sql = "UPDATE PRODUCT SET PRODUCT_NAME = ?, PRODUCT_DESC = ?, PRICE = ?, STOCK = ? WHERE PRODUCT_ID = ? ";
            PreparedStatement statement = con.prepareStatement(sql);
            
            statement.setString(1, productName);
            statement.setString(2, productDesc);
            statement.setDouble(3, priceAdd);
            statement.setInt(4, stockAdd);
            statement.setInt(5, productID);
            
            //st.executeUpdate("UPDATE PRODUCT( PRODUCT_NAME,PRODUCT_DESC, PRICE, STOCK) VALUES('" +  "','" + productName + "','" + productDesc + "','" + priceAdd + "','" + stockAdd + "') WHERE PRODUCT_ID ="+productID);
            //st.executeUpdate("UPDATE PRODUCT SET PRODUCT_NAME = ?, PRODUCT_DESC = ?, PRICE = ?, STOCK = ? WHERE PRODUCT_ID = ? "); 
            JOptionPane.showMessageDialog(null, "product edited!");
        }
        catch (SQLException e1){
            JOptionPane.showMessageDialog(null, e1);
        }    
        

// TODO add your handling code here:
    }//GEN-LAST:event_EditProd_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPod_btn;
    private javax.swing.JLabel Category;
    private javax.swing.JButton DeleteProd_btn;
    private javax.swing.JLabel Description;
    private javax.swing.JButton EditProd_btn;
    private javax.swing.JButton LogOut_btn;
    private javax.swing.JLabel Price;
    private javax.swing.JTextField ProdCategory_txt;
    private javax.swing.JTextField ProdDescript_txt;
    private javax.swing.JLabel ProdID;
    private javax.swing.JTextField ProdID_txt;
    private javax.swing.JLabel ProdNAme;
    private javax.swing.JTextField ProdName_txt;
    private javax.swing.JTextField ProdPrice_txt;
    private javax.swing.JTextField ProdQuantity_txt;
    private javax.swing.JTable ProductList;
    private javax.swing.JButton Products_btn;
    private javax.swing.JLabel Quantity;
    private javax.swing.JButton SalesClerk_btn;
    private javax.swing.JButton Statistics;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
