import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shuaib UWC
 */
public class SalesClerk extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public SalesClerk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Products_btn = new javax.swing.JButton();
        SalesClerk_btn = new javax.swing.JButton();
        Statistics = new javax.swing.JButton();
        LogOut_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SellerID = new javax.swing.JLabel();
        SellerPassword = new javax.swing.JLabel();
        SallerID_txt = new javax.swing.JTextField();
        SallerPass_txt = new javax.swing.JTextField();
        AddClerk_btn = new javax.swing.JButton();
        DeleteClerk_btn = new javax.swing.JButton();
        EditClerk_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SalesClerk_table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        SalesClerk_clsbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Products_btn.setBackground(new java.awt.Color(0, 0, 204));
        Products_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Products_btn.setForeground(new java.awt.Color(204, 255, 255));
        Products_btn.setText("PRODUCTS");
        Products_btn.setBorder(null);
        Products_btn.setContentAreaFilled(false);
        Products_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Products_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Products_btnActionPerformed(evt);
            }
        });
        jPanel2.add(Products_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 150, 31));

        SalesClerk_btn.setBackground(new java.awt.Color(0, 0, 204));
        SalesClerk_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SalesClerk_btn.setForeground(new java.awt.Color(204, 255, 255));
        SalesClerk_btn.setText("SALES CLERK");
        SalesClerk_btn.setBorder(null);
        SalesClerk_btn.setContentAreaFilled(false);
        SalesClerk_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(SalesClerk_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 150, 31));

        Statistics.setBackground(new java.awt.Color(0, 0, 204));
        Statistics.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Statistics.setForeground(new java.awt.Color(204, 255, 255));
        Statistics.setText("STATISTICS");
        Statistics.setBorder(null);
        Statistics.setContentAreaFilled(false);
        Statistics.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Statistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatisticsActionPerformed(evt);
            }
        });
        jPanel2.add(Statistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 150, 31));

        LogOut_btn.setBackground(new java.awt.Color(0, 0, 204));
        LogOut_btn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        LogOut_btn.setForeground(new java.awt.Color(255, 0, 0));
        LogOut_btn.setText("LOG OUT");
        LogOut_btn.setBorder(null);
        LogOut_btn.setContentAreaFilled(false);
        LogOut_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut_btnActionPerformed(evt);
            }
        });
        jPanel2.add(LogOut_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 150, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("DESIGNED BY TRENTECH");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 150, 20));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Sales Clerk");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 11, 210, -1));

        SellerID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SellerID.setForeground(new java.awt.Color(0, 0, 204));
        SellerID.setText("Seller ID");
        jPanel3.add(SellerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        SellerPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SellerPassword.setForeground(new java.awt.Color(0, 0, 204));
        SellerPassword.setText("Password");
        jPanel3.add(SellerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 88, 30));

        SallerID_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SallerID_txtActionPerformed(evt);
            }
        });
        jPanel3.add(SallerID_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 108, 140, -1));
        jPanel3.add(SallerPass_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 152, 140, -1));

        AddClerk_btn.setBackground(new java.awt.Color(0, 0, 204));
        AddClerk_btn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        AddClerk_btn.setForeground(new java.awt.Color(204, 255, 255));
        AddClerk_btn.setText("ADD");
        AddClerk_btn.setBorder(null);
        AddClerk_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddClerk_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClerk_btnActionPerformed(evt);
            }
        });
        jPanel3.add(AddClerk_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 214, 83, 36));

        DeleteClerk_btn.setBackground(new java.awt.Color(0, 0, 204));
        DeleteClerk_btn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        DeleteClerk_btn.setForeground(new java.awt.Color(204, 255, 255));
        DeleteClerk_btn.setText("DELETE");
        DeleteClerk_btn.setBorder(null);
        DeleteClerk_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteClerk_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteClerk_btnActionPerformed(evt);
            }
        });
        jPanel3.add(DeleteClerk_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 214, 88, 36));

        EditClerk_btn.setBackground(new java.awt.Color(0, 0, 204));
        EditClerk_btn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        EditClerk_btn.setForeground(new java.awt.Color(204, 255, 255));
        EditClerk_btn.setText("EDIT");
        EditClerk_btn.setBorder(null);
        EditClerk_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditClerk_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditClerk_btnActionPerformed(evt);
            }
        });
        jPanel3.add(EditClerk_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 214, 81, 36));

        SalesClerk_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SELLER ID", "PASSWORD"
            }
        ));
        SalesClerk_table.setSelectionBackground(new java.awt.Color(0, 0, 204));
        jScrollPane1.setViewportView(SalesClerk_table);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 394, 818, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("SALES CLERK");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 361, 121, -1));

        SalesClerk_clsbtn.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        SalesClerk_clsbtn.setForeground(new java.awt.Color(255, 0, 0));
        SalesClerk_clsbtn.setText("X");
        SalesClerk_clsbtn.setBorder(null);
        SalesClerk_clsbtn.setBorderPainted(false);
        SalesClerk_clsbtn.setContentAreaFilled(false);
        SalesClerk_clsbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalesClerk_clsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesClerk_clsbtnActionPerformed(evt);
            }
        });
        jPanel3.add(SalesClerk_clsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(962, 0, 38, 28));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddClerk_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClerk_btnActionPerformed
        if (SallerID_txt.getText().isEmpty() || SallerPass_txt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill in all fields!");
        }// TODO add your handling code here:
    }//GEN-LAST:event_AddClerk_btnActionPerformed

    private void SallerID_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SallerID_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SallerID_txtActionPerformed

    private void SalesClerk_clsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesClerk_clsbtnActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_SalesClerk_clsbtnActionPerformed

    private void Products_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Products_btnActionPerformed
        setVisible(false);
        new Admin().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_Products_btnActionPerformed

    private void StatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatisticsActionPerformed
       setVisible(false);
       new Statistics().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_StatisticsActionPerformed

    private void LogOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOut_btnActionPerformed
        setVisible(false);
        new LoginPage().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_LogOut_btnActionPerformed

    private void DeleteClerk_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteClerk_btnActionPerformed
        if (SallerID_txt.getText().isEmpty() || SallerPass_txt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please select as valid user to delete!");
        }// TODO add your handling code here:
    }//GEN-LAST:event_DeleteClerk_btnActionPerformed

    private void EditClerk_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditClerk_btnActionPerformed
        if (SallerID_txt.getText().isEmpty() || SallerPass_txt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please select a valid user to edit!");
        }// TODO add your handling code here:
    }//GEN-LAST:event_EditClerk_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesClerk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddClerk_btn;
    private javax.swing.JButton DeleteClerk_btn;
    private javax.swing.JButton EditClerk_btn;
    private javax.swing.JButton LogOut_btn;
    private javax.swing.JButton Products_btn;
    private javax.swing.JButton SalesClerk_btn;
    private javax.swing.JButton SalesClerk_clsbtn;
    private javax.swing.JTable SalesClerk_table;
    private javax.swing.JTextField SallerID_txt;
    private javax.swing.JTextField SallerPass_txt;
    private javax.swing.JLabel SellerID;
    private javax.swing.JLabel SellerPassword;
    private javax.swing.JButton Statistics;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
