import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shuaib UWC
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LogOut_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SellerID = new javax.swing.JLabel();
        SellerPassword = new javax.swing.JLabel();
        ProdName_txt = new javax.swing.JTextField();
        ProdID_txt = new javax.swing.JTextField();
        AddClerk_btn = new javax.swing.JButton();
        DeleteClerk_btn = new javax.swing.JButton();
        Print_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserProduct_table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        SalesClerk_clsbtn = new javax.swing.JButton();
        SellerPassword1 = new javax.swing.JLabel();
        Quantity_txt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Invoice = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogOut_btn.setBackground(new java.awt.Color(0, 0, 204));
        LogOut_btn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        LogOut_btn.setForeground(new java.awt.Color(255, 0, 0));
        LogOut_btn.setText("LOG OUT");
        LogOut_btn.setBorder(null);
        LogOut_btn.setContentAreaFilled(false);
        LogOut_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut_btnActionPerformed(evt);
            }
        });
        jPanel2.add(LogOut_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 140, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("DESIGNED BY TRENTECH");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 150, 20));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Sales");

        SellerID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SellerID.setForeground(new java.awt.Color(0, 0, 204));
        SellerID.setText("Product Name");

        SellerPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SellerPassword.setForeground(new java.awt.Color(0, 0, 204));
        SellerPassword.setText("Product ID");

        ProdName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdName_txtActionPerformed(evt);
            }
        });

        ProdID_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdID_txtActionPerformed(evt);
            }
        });

        AddClerk_btn.setBackground(new java.awt.Color(0, 0, 204));
        AddClerk_btn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        AddClerk_btn.setForeground(new java.awt.Color(204, 255, 255));
        AddClerk_btn.setText("ADD");
        AddClerk_btn.setBorder(null);
        AddClerk_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddClerk_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClerk_btnActionPerformed(evt);
            }
        });

        DeleteClerk_btn.setBackground(new java.awt.Color(0, 0, 204));
        DeleteClerk_btn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        DeleteClerk_btn.setForeground(new java.awt.Color(204, 255, 255));
        DeleteClerk_btn.setText("DELETE");
        DeleteClerk_btn.setBorder(null);
        DeleteClerk_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Print_btn.setBackground(new java.awt.Color(0, 0, 204));
        Print_btn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Print_btn.setForeground(new java.awt.Color(204, 255, 255));
        Print_btn.setText("PRINT");
        Print_btn.setBorder(null);
        Print_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Print_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_btnActionPerformed(evt);
            }
        });

        UserProduct_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT NAME", "PRODUCT ID", "PRICE"
            }
        ));
        UserProduct_table.setSelectionBackground(new java.awt.Color(0, 0, 204));
        jScrollPane1.setViewportView(UserProduct_table);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("PRODUCT LIST");

        SalesClerk_clsbtn.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        SalesClerk_clsbtn.setForeground(new java.awt.Color(255, 0, 0));
        SalesClerk_clsbtn.setText("X");
        SalesClerk_clsbtn.setBorder(null);
        SalesClerk_clsbtn.setBorderPainted(false);
        SalesClerk_clsbtn.setContentAreaFilled(false);
        SalesClerk_clsbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalesClerk_clsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesClerk_clsbtnActionPerformed(evt);
            }
        });

        SellerPassword1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SellerPassword1.setForeground(new java.awt.Color(0, 0, 204));
        SellerPassword1.setText("Quantity");

        Invoice.setColumns(20);
        Invoice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Invoice.setRows(5);
        Invoice.setText("=========RETAIL SURVEYOR SYSTEM======\n================================\n\nP Name\t    Quantity    \t      Price\t    total\n__________________________________________");
        jScrollPane2.setViewportView(Invoice);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SellerPassword1)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SellerID, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(SellerPassword)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Quantity_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(ProdID_txt)
                                    .addComponent(ProdName_txt)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(AddClerk_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteClerk_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(422, 422, 422)
                        .addComponent(SalesClerk_clsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Print_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(SalesClerk_clsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ProdName_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(SellerID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProdID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SellerPassword))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Quantity_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SellerPassword1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddClerk_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteClerk_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Print_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddClerk_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClerk_btnActionPerformed
        if (ProdName_txt.getText().isEmpty() || ProdID_txt.getText().isEmpty() || Quantity_txt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill in all fields");
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_AddClerk_btnActionPerformed

    private void ProdName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdName_txtActionPerformed

    private void SalesClerk_clsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesClerk_clsbtnActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_SalesClerk_clsbtnActionPerformed

    private void Print_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_btnActionPerformed
        try{
            Invoice.print();
        }
        catch(Exception e){
        }// TODO add your handling code here:
    }//GEN-LAST:event_Print_btnActionPerformed

    private void ProdID_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdID_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdID_txtActionPerformed

    private void LogOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOut_btnActionPerformed
        setVisible(false);
        new LoginPage().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_LogOut_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddClerk_btn;
    private javax.swing.JButton DeleteClerk_btn;
    private javax.swing.JTextArea Invoice;
    private javax.swing.JButton LogOut_btn;
    private javax.swing.JButton Print_btn;
    private javax.swing.JTextField ProdID_txt;
    private javax.swing.JTextField ProdName_txt;
    private javax.swing.JTextField Quantity_txt;
    private javax.swing.JButton SalesClerk_clsbtn;
    private javax.swing.JLabel SellerID;
    private javax.swing.JLabel SellerPassword;
    private javax.swing.JLabel SellerPassword1;
    private javax.swing.JTable UserProduct_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
